### ISSUE TITLE
Màj Librairies & appel par API

### ISSUE THREAD

**Issue by angelinepi** [angelinepi/atelier-sigat-plan-campus-R2#10]
Gestion de librairies / framework par appels URL plutôt que stocker le fichier en local
- css/bootstrap.min.css
replaced by : <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

-  ./js/bootstrap.min.js
replaced by :  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.2/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

Fichiers inutiles :
- js\mapbox-gl.js
- js\maplibre-gl.js

**Comment by pbsnrd** [comment]
Autres fichiers inutiles : 
Morris n'est pas appelé dans l'html (morris utilisé pour faire des graphiques) 
- morris.css
- morris.min.js
- morris.data.js 

- mapbox-gl (tous car on utilise maplibre) 

- appel de : bootstrap.min.css par url et pas en local 

-jquery.min.map : fichier seulement texte, pas appelé dans l'html

faire de tris dans le dossier font ? 
- fontfaces.css pas appelé dans l'html

**Comment by angelinepi** [comment]
Update de l'issue : faire la mise à jour des librairies
et passer par l'appel api
notamment pour MapLibre

**Comment by angelinepi** [comment]
Petit problème avec le passage la librairie MapLibre 4
> loadImage semble pas fonctionner sur des images locales 
https://github.com/mapbox/mapbox-gl-js/issues/8037

> les listes de couches ont pas l'air de fonctionner non plus
Error: The layer does not exist in the map's style and cannot be queried for features.
https://github-com.translate.goog/mapbox/mapbox-gl-js/issues/4222?_x_tr_sl=en&_x_tr_tl=fr&_x_tr_hl=fr&_x_tr_pto=sc#issuecomment-279446075
