### ISSUE TITLE
#Bug - images batiments KO

### ISSUE THREAD

**Issue by angelinepi** [angelinepi/atelier-sigat-plan-campus-R2#16]
![image](https://github.com/angelinepi/atelier-sigat-plan-campus-R2/assets/157594445/944bdd8a-a2b3-4077-b8b0-658845ba6b79)

Voir dans la fonction getPopupContent(feature) peut-être ?
notamment les dernières lignes des conditionnelles :

(...)
    if (feature.properties.Image !== "null" && feature.properties.Image !== null && feature.properties.Image !== "") {
      if (feature.properties.Categorie == 'Département de formation') {
        popupTitle += '<img style = \'height : 60px; position : absolute; right : 0;top:0\' src = \'' + feature.properties.Image + '\'/>'
      }
      else if (feature.properties.Categorie == 'Oeuvre') {
        popupContent += '<img style = \'height : auto; width : 96%; margin-left:2%; margin-right:2%; margin-bottom: 4px;\' src = \'' + feature.properties.Image + '\'/>'
      }
      else {
        popupContent += '<img style = \'height : 60px; left : 50%\' src = \'' + feature.properties.Image + '\'/>'
      }
    }
  }

**Comment by pbsnrd** [comment]
j'ai fait une pull request : le probleme était que le chemin appeler était <img src = 'photos/batE.jpg?v=14032024'/> pourtant notre dossier s'appelle photo sans s 
j'ai ajouter un console.log mis en commentaire dans le code où il y a l'appel de l'image 
(je sais pas si ca joue un problème ailleurs)
