### ISSUE TITLE
#Bug - 2D->3D->2D

### ISSUE THREAD

**Issue by angelinepi** [angelinepi/atelier-sigat-plan-campus-R2#17]
1. passage 3D manque animation inclinaison
2. retour en 2D KO.

**Comment by pbsnrd** [comment]
merci alors le pb vient d'ici : 
plan.js:2555 Uncaught ReferenceError: DDButton is not defined
    at plan.js:2555:12
    at plan.js:2718:3

les boutons 2D et 3D sont crées dans le JS, tout semble correct

**Comment by angelinepi** [comment]
//ajout de couches
    if (!map.getSource("bati2D") {
      map.addSource("bati2D", {
        type: "geojson",
        data: "../data/bati/Bati_2D.geojson?v="+version
      });
    }
    
    Vu avec Adrien P
