### ISSUE TITLE
#Bug - Réinitialisation des filtres

### ISSUE THREAD

**Issue by angelinepi** [angelinepi/atelier-sigat-plan-campus-R2#6]
Tous les filtres ne s'effacent pas quand on clique "réinitialiser les filtres".

Ex. Si je sélectionne tous les URF et clique "réinitialiser les filtres", uniquement un filtre est retiré (sciences sociales).

**Comment by angelinepi** [comment]
Le bug n'a pas encore été tout à fait corrigé suite à l'intervention d'AdrienP.
1) premier clic : réduit la liste de la side bar
2) deuxième clic : efface les filtres

**Comment by X4ndre2** [comment]
C'est debug la team
